// packages/vue-datatable/src/components/dataTable.vue
<template>
    <div>
        <slot></slot>
        <div v-for="row in data" v-bind:key="row.id">
            <dataCell v-for="column in columns"
                v-bind:key="column.field"
                v-bind:id="row.id"
                v-bind:field="column.field"
                v-bind:value="row[column.field]"
                v-bind:editable="column.editable"
                />
        </div>
    </div>
</template>

<script>
import dataCell from './dataCell'

export default {
    name: 'DataTable',
    components: { dataCell },
    props: {
        data: Array
    },
    data: function () {
        return {
            columns: []
        }
    },
    mounted: function () {
        const columns = this.$children.map(column => {
            const field = column.$props.field
            const label = column.$props.label
            const editable = column.$props.editable
            return { field, label, editable }
        })
        this.columns = columns
    }
}
</script>

<style>
  dataTable {
    border: 1px solid red;
    padding: 5px;
    text-align: center;
  }
</style>

// packages/react-datatable/src/DataTable.js
import React from 'react';
import './DataTable.css';
import { DataCell } from './DataCell';

export class DataTable extends React.Component {
    render() {
        const columns = this.props.children.map(column => {
            const field = column.props.field;
            const label = column.props.label;
            const editable = column.props.editable;
            return { field, label, editable };
        });

        return (
            <div className="dataTable">
                {this.props.children}
                <div className="table">
                    {(this.props.data || []).map(row => {
                        const cells = columns.map(column => {
                            return <DataCell key={row.id} id={row.id} field={column.field} value={row[column.field]} editable={column.editable} onChange={this.props.onChange} />;
                        });
                        return <div>{cells}</div>
                    })}
                </div>
            </div>
        );
    }
}
