// packages/vue-datatable/src/components/dataCell.vue
<template>
    <span>
        <input
            v-bind:class="classList"
            v-bind:readonly="readOnly"
            v-model.lazy.trim="modelValue"
            v-on:dblclick="handleDoubleClick"
            v-on:blur="handleBlur"
            v-on:keydown="handleKeyDown">
    </span>
</template>

<script>
export default {
    name: 'DataCell',
    props: {
        id: [String, Number],
        field: String,
        value: [String, Number],
        editable: Boolean
    },
    data: function () {
        return {
            classList: 'view',
            readOnly: true,
            modelValue: this.value
        }
    },
    methods: {
        setEditMode: function (enabled) {
            this.readOnly = !enabled
            this.classList = enabled ? 'edit' : 'view'
        },
        handleDoubleClick: function (evt) {
            if (this.editable) {
                this.setEditMode(true)
            }
        },
        handleKeyDown: function (evt) {
            if (evt.key === 'Enter' && this.editable) {
                this.setEditMode(false)
                this.dispatchSave()
            }
        },
        handleBlur: function (evt) {
            if (this.editable) {
                this.setEditMode(false)
                this.dispatchSave()
            }
        },
        dispatchSave: function () {
            if (this.value !== this.modelValue) {
                console.warn('UPDATE', this.id, this.field, this.value, this.modelValue)
                this.$emit('update:value', this.modelValue)
            }
        }
    }
}
</script>

<style>
.view {
	margin-left: 5px;
	padding: 2px;
	border: none;
	flex: 5;
}
.edit {
	margin-left: 5px;
	padding: 2px;
	border: none;
	color: white;
	border-bottom: 2px #ff3f91 solid;
	flex: 5;
	background-color: hotpink;
}
</style>

// packages/react-datatable/src/DataCell.js
import React from 'react';
import './DataCell.css'

export class DataCell extends React.Component {
    constructor(props, context) {
        super(props, context)
        // initial component state
        this.state = { value: this.props.value || '', className: 'view', readOnly: true }
        // create bound functions for event handlers
        this.handleDoubleClick = this.handleDoubleClick.bind(this)
        this.handleBlur = this.handleBlur.bind(this)
        this.handleChange = this.handleChange.bind(this)
        this.handleKeyDown = this.handleKeyDown.bind(this)
    }

    render() {
        return (
            <input className={this.state.className}
                value={this.state.value}
                readOnly={this.state.readOnly}
                onDoubleClick={this.handleDoubleClick}
                onBlur={this.handleBlur}
                onChange={this.handleChange}
                onKeyDown={this.handleKeyDown}
            >
            </input>
        )
    }

    setEditMode(enabled) {
        this.setState({ readOnly: !enabled, className: enabled ? 'edit' : 'view' });
    }

    handleDoubleClick() {
        if (this.props.editable) {
            this.setEditMode(true);
        }
    }

    handleChange(evt) {
        this.setState({ value: evt.target.value.trim() });
    }

    handleKeyDown(evt) {
        if (evt.key === 'Enter' && !this.state.readOnly) {
            this.setEditMode(false);
            this.dispatchSave(this.state.value);
        }
    }

    handleBlur() {
        if (!this.state.readOnly) {
            this.setEditMode(false);
            this.dispatchSave(this.state.value);
        }
    }
    dispatchSave(value) {
        if (this.props.onChange) {
            this.props.onChange(this.props.id, this.props.field, value);
        }
    }
}
